import type { Metadata } from "next";
import { ColorModeScript } from "@yamada-ui/react";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ColorModeScript />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
